version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - webnet
    restart: always
    depends_on:
      - wordpress
    volumes :
      - ./data/wordpress_files:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - ./data/wordpress_files:/var/www/html
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_pass
      - WORDPRESS_DB_NAME=wp_database
    networks:
      - webnet
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "9000:9000"

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=hrobin
      - MYSQL_DATABASE=wp_database
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=wp_pass
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  webnet:
    driver: bridge
